# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'question_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_question_form(object):
    def setupUi(self, question_form):
        question_form.setObjectName("question_form")
        question_form.resize(480, 96)
        question_form.setMinimumSize(QtCore.QSize(480, 96))
        question_form.setBaseSize(QtCore.QSize(480, 360))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        question_form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_res/excel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        question_form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(question_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_label = QtWidgets.QLabel(question_form)
        self.text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.text_label.setObjectName("text_label")
        self.verticalLayout.addWidget(self.text_label)
        self.horizontal_widget = QtWidgets.QHBoxLayout()
        self.horizontal_widget.setObjectName("horizontal_widget")
        self.button_no = QtWidgets.QPushButton(question_form)
        self.button_no.setObjectName("button_no")
        self.horizontal_widget.addWidget(self.button_no)
        self.button_ok = QtWidgets.QPushButton(question_form)
        self.button_ok.setObjectName("button_ok")
        self.horizontal_widget.addWidget(self.button_ok)
        self.verticalLayout.addLayout(self.horizontal_widget)

        self.retranslateUi(question_form)
        QtCore.QMetaObject.connectSlotsByName(question_form)

    def retranslateUi(self, question_form):
        _translate = QtCore.QCoreApplication.translate
        question_form.setWindowTitle(_translate("question_form", "Question"))
        self.text_label.setText(_translate("question_form", "The text of question!"))
        self.button_no.setText(_translate("question_form", "NO"))
        self.button_ok.setText(_translate("question_form", "OK"))
import resourses_rc
