# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_form(object):
    def setupUi(self, settings_form):
        settings_form.setObjectName("settings_form")
        settings_form.resize(600, 480)
        settings_form.setMinimumSize(QtCore.QSize(600, 480))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        settings_form.setFont(font)
        settings_form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon_res/excel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        settings_form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(settings_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget = QtWidgets.QTabWidget(settings_form)
        self.tab_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_widget.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.label_regular = QtWidgets.QLabel(self.tab)
        self.label_regular.setStyleSheet("padding: 5px;")
        self.label_regular.setObjectName("label_regular")
        self.gridLayout.addWidget(self.label_regular, 1, 0, 1, 1)
        self.edit_regular = QtWidgets.QLineEdit(self.tab)
        self.edit_regular.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"padding: 5px;")
        self.edit_regular.setObjectName("edit_regular")
        self.gridLayout.addWidget(self.edit_regular, 1, 1, 1, 1)
        self.label_zip = QtWidgets.QLabel(self.tab)
        self.label_zip.setStyleSheet("padding: 5px;")
        self.label_zip.setObjectName("label_zip")
        self.gridLayout.addWidget(self.label_zip, 2, 0, 1, 1)
        self.edit_zip = QtWidgets.QLineEdit(self.tab)
        self.edit_zip.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"padding: 5px;")
        self.edit_zip.setObjectName("edit_zip")
        self.gridLayout.addWidget(self.edit_zip, 2, 1, 1, 1)
        self.edit_info = QtWidgets.QTextEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_info.sizePolicy().hasHeightForWidth())
        self.edit_info.setSizePolicy(sizePolicy)
        self.edit_info.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.edit_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.edit_info.setFrameShadow(QtWidgets.QFrame.Plain)
        self.edit_info.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.edit_info.setUndoRedoEnabled(False)
        self.edit_info.setAcceptRichText(False)
        self.edit_info.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.edit_info.setObjectName("edit_info")
        self.gridLayout.addWidget(self.edit_info, 3, 0, 1, 2)
        self.label_html = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_html.sizePolicy().hasHeightForWidth())
        self.label_html.setSizePolicy(sizePolicy)
        self.label_html.setStyleSheet("padding: 5px;")
        self.label_html.setAlignment(QtCore.Qt.AlignCenter)
        self.label_html.setObjectName("label_html")
        self.gridLayout.addWidget(self.label_html, 0, 0, 1, 2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon_res/html.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.tab, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_zipconfig = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_zipconfig.sizePolicy().hasHeightForWidth())
        self.label_zipconfig.setSizePolicy(sizePolicy)
        self.label_zipconfig.setStyleSheet("padding: 5px;")
        self.label_zipconfig.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zipconfig.setObjectName("label_zipconfig")
        self.gridLayout_2.addWidget(self.label_zipconfig, 0, 0, 1, 1)
        self.check_run = QtWidgets.QCheckBox(self.tab_2)
        self.check_run.setStyleSheet("padding: 5px;")
        self.check_run.setChecked(True)
        self.check_run.setObjectName("check_run")
        self.gridLayout_2.addWidget(self.check_run, 1, 0, 1, 1)
        self.check_zip = QtWidgets.QCheckBox(self.tab_2)
        self.check_zip.setStyleSheet("padding: 5px;")
        self.check_zip.setObjectName("check_zip")
        self.gridLayout_2.addWidget(self.check_zip, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(532, 330, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon_res/zip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab_widget.addTab(self.tab_2, icon2, "")
        self.verticalLayout.addWidget(self.tab_widget)
        self.horizontal_layout = QtWidgets.QHBoxLayout()
        self.horizontal_layout.setObjectName("horizontal_layout")
        self.upload_btn = QtWidgets.QPushButton(settings_form)
        self.upload_btn.setStyleSheet("padding: 5px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon_res/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upload_btn.setIcon(icon3)
        self.upload_btn.setObjectName("upload_btn")
        self.horizontal_layout.addWidget(self.upload_btn)
        self.clear_btn = QtWidgets.QPushButton(settings_form)
        self.clear_btn.setStyleSheet("padding: 5px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon_res/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_btn.setIcon(icon4)
        self.clear_btn.setObjectName("clear_btn")
        self.horizontal_layout.addWidget(self.clear_btn)
        self.save_btn = QtWidgets.QPushButton(settings_form)
        self.save_btn.setStyleSheet("padding: 5px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon_res/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon5)
        self.save_btn.setObjectName("save_btn")
        self.horizontal_layout.addWidget(self.save_btn)
        self.uses_btn = QtWidgets.QPushButton(settings_form)
        self.uses_btn.setStyleSheet("padding: 5px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon_res/uses.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uses_btn.setIcon(icon6)
        self.uses_btn.setObjectName("uses_btn")
        self.horizontal_layout.addWidget(self.uses_btn)
        self.verticalLayout.addLayout(self.horizontal_layout)

        self.retranslateUi(settings_form)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(settings_form)

    def retranslateUi(self, settings_form):
        _translate = QtCore.QCoreApplication.translate
        settings_form.setWindowTitle(_translate("settings_form", "Настройки"))
        self.label_regular.setText(_translate("settings_form", "<html><head/><body><p><span style=\" font-weight:600;\">Наименование отчета:</span></p></body></html>"))
        self.edit_regular.setText(_translate("settings_form", "REPORT_START-STOP_RYEARS"))
        self.label_zip.setText(_translate("settings_form", "<html><head/><body><p><span style=\" font-weight:600;\">Наименование папки с архивом:</span></p></body></html>"))
        self.edit_zip.setText(_translate("settings_form", "Архив_START-STOP_RYEARS"))
        self.edit_info.setHtml(_translate("settings_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt;\">В данных строках настроек используютя регулярные выражения</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt;\">для замены конкретного текста на предустановленный.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt;\">Для настройки имён отчётов вы можете использовать следующие имена</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt;\">регулярных выражений.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt;\">Данные замены являются фиксированными </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt;\">и никак не могут быть изменены.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt; font-weight:600;\">REPORT</span><span style=\" font-family:\'Arial\'; font-size:12pt;\"> - заменяется на &quot;Сводная-таблица&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt; font-weight:600;\">START</span><span style=\" font-family:\'Arial\'; font-size:12pt;\"> - Начальный месяц отчёта.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt; font-weight:600;\">STOP</span><span style=\" font-family:\'Arial\'; font-size:12pt;\"> - Конечный месяц отчёта.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt; font-weight:600;\">CDAY</span><span style=\" font-family:\'Arial\'; font-size:12pt;\"> - Дата текущего дня, только одного дня.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt; font-weight:600;\">CMONTH</span><span style=\" font-family:\'Arial\'; font-size:12pt;\"> - Дата текущего месяца, только одного месяца.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt; font-weight:600;\">CYEARS</span><span style=\" font-family:\'Arial\'; font-size:12pt;\"> - Дата текущего года, только одного года.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt; font-weight:600;\">CDATE</span><span style=\" font-family:\'Arial\'; font-size:12pt;\"> - Полная текущая дата в формате &quot;день.месяц.год&quot;, например 01.01.2024.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:12pt; font-weight:600;\">RYEARS</span><span style=\" font-family:\'Arial\'; font-size:12pt;\"> - Год, полученный из настроек excel файла.</span></p></body></html>"))
        self.label_html.setText(_translate("settings_form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Настройки отчётности.</span></p></body></html>"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("settings_form", "html"))
        self.label_zipconfig.setText(_translate("settings_form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Настройки архивов.</span></p></body></html>"))
        self.check_run.setText(_translate("settings_form", "Открыть отчёт после создания"))
        self.check_zip.setText(_translate("settings_form", "Открыть папку с архивом после формирования"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("settings_form", "Архивы"))
        self.upload_btn.setText(_translate("settings_form", "Перезагрузить"))
        self.clear_btn.setText(_translate("settings_form", "Сбросить"))
        self.save_btn.setText(_translate("settings_form", "Сохранить"))
        self.uses_btn.setText(_translate("settings_form", "Применить"))
import resourses_rc
